### ISSUE TITLE
Networking with blockade - restrict communication

### ISSUE THREAD

**Issue by arneboockmeyer** [worstcase/blockade#69]
Hi,

lets say, we are using this configuration:
```
containers:
  c1:
    image: my_docker_image

  c2:
    image: my_docker_image
    links: ["c1"]

  c3:
    image: my_docker_image
    links: ["c2"]
```

In our understanding of the documentation, `c2` should be able to communicate with `c1` and `c3` and `c3` should be able to communicate with `c2` but not with `c1` (since they are not linked).

We tested this configuration and we were wondered that every machine can communicate with every other one. Do we misunderstand the documentation (part `links`) or  is this a bug? If we misunderstand the documentation, how can we archive our goal?

Thanks for your help!
